---

# ansible-playbook -i inventories/localhost pb_provision.yml

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws_vpc
    - aws_vpc_nat_gateway
    - aws_vpc_route_tables
    - aws_vpc_nacl
#    - aws_security_groups
#    - aws_ec2_key_pairs
#    - aws_iam_roles
#    - aws_ec2
