---

- name: creating vpc
  local_action:
    module: ec2_vpc
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    state: present
    cidr_block: 10.123.0.0/16
    resource_tags:
      Name: "{{ aws_project }}"
    subnets:
      - cidr: 10.123.1.0/24
        az: us-east-1b
        resource_tags: { "Name" : "{{ aws_project }}_public" }
      - cidr: 10.123.2.0/24
        az: us-east-1b
        resource_tags: { "Name" : "{{ aws_project }}_private" }
    internet_gateway: True
  register: aws_vpc

- debug: var=aws_vpc