---

- name: set random subnet
  set_fact:
    prv_subnet="{{ aws_vpc.subnets | random }}"

- name: provision node
  ec2:
    profile: bot
    region: "{{ aws_region }}"
    key_name: bot
    groups:
      - ssh
    instance_type: t2.small
    image: "{{ aws_ami }}"
    wait: yes
    wait_timeout: 600
    instance_profile_name: bot
    instance_tags:
      Name: bot
    exact_count: 1
    count_tag:
      Name: bot
    ebs_optimized: no
    monitoring: no
    vpc_subnet_id: "{{ prv_subnet.id }}"
    assign_public_ip: yes
  register: ec2

- name: wait for SSH to come up
  wait_for: >
    host="{{ item.public_ip }}"
    port=22
    delay=1
    timeout=300
    state=started
  with_items: "{{ ec2.tagged_instances }}"